"""Pure shared protocol core for dataset-specific R2SP experiments."""

from .fingerprint import (
    CodeFileFingerprint,
    CodeFingerprint,
    fingerprint_code_roots,
    fingerprint_code_tree,
)
from .full_doc_retrieval import (
    FullDocumentHybridSession,
    FullDocumentRankedIndex,
    FullDocumentSearchEvent,
    serialize_full_document_response,
)
from .isolation import (
    ResetAttestation,
    ResetAttestationError,
    ResetCheck,
    ResetEvidence,
    RuntimeIdentity,
    attest_reset,
)
from .protocol import (
    HybridCandidate,
    HybridSearchEvent,
    Page,
    PageSnippet,
    PublicTrace,
    SearchEvent,
    SearchHit,
    TraceEvent,
)
from .retrieval import (
    DeterministicBM25,
    HybridRetrievalInvalid,
    HybridSessionWebRetriever,
    InvalidQueryError,
    OpenBudgetExceeded,
    OpenPagesAlreadyCalledError,
    OpenPagesValidationError,
    OpenSelectionRequiredError,
    PageNotExposedError,
    RankedPageIndex,
    RetrievalError,
    RetrieverClosedError,
    SearchAfterOpenError,
    SearchBudgetExceeded,
    SessionWebRetriever,
    reciprocal_rank_fusion,
    tokenize,
)
from .status import RunStatus, parse_run_status

__all__ = [
    "CodeFileFingerprint",
    "CodeFingerprint",
    "DeterministicBM25",
    "FullDocumentHybridSession",
    "FullDocumentRankedIndex",
    "FullDocumentSearchEvent",
    "HybridCandidate",
    "HybridRetrievalInvalid",
    "HybridSearchEvent",
    "HybridSessionWebRetriever",
    "InvalidQueryError",
    "OpenBudgetExceeded",
    "OpenPagesAlreadyCalledError",
    "OpenPagesValidationError",
    "OpenSelectionRequiredError",
    "Page",
    "PageNotExposedError",
    "PageSnippet",
    "PublicTrace",
    "RankedPageIndex",
    "ResetAttestation",
    "ResetAttestationError",
    "ResetCheck",
    "ResetEvidence",
    "RetrievalError",
    "RetrieverClosedError",
    "RunStatus",
    "RuntimeIdentity",
    "SearchAfterOpenError",
    "SearchBudgetExceeded",
    "SearchEvent",
    "SearchHit",
    "SessionWebRetriever",
    "TraceEvent",
    "attest_reset",
    "fingerprint_code_roots",
    "fingerprint_code_tree",
    "parse_run_status",
    "reciprocal_rank_fusion",
    "serialize_full_document_response",
    "tokenize",
]

__version__ = "0.1.0"
